name: Run Autorun Daily Script

on:
  schedule:
    - cron: "46 16 * * *" # Run daily at 17:46 CET (adjusted for UTC during winter)
    #- cron: "46 15 * * *" # Run daily at 17:46 CEST (adjusted for UTC during summer)
  workflow_dispatch: # Optional: Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.10" # Recommended stable version for broad compatibility

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install --force-reinstall -r requirements.txt; fi

      # Step 4: Run the Python script
      - name: Run autorun_daily.py
        run: python autorun_daily.py
