name: Run Autorun Daily Script

on:
  schedule:
    - cron: "46 16 * * *" # Run daily at 17:46 CET
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script and generate plots
        run: |
          python autorun_daily.py

      - name: Verify generated plots
        run: |
          echo "Checking for generated plots..."
          ls -la "daily heatmap"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add "daily heatmap/"
          git commit -m "Add daily plots for $(date +'%Y-%m-%d')"
          git push origin main 
