name: Run Autorun Daily Script

on:
  schedule:
    - cron: "46 15 * * *" # Run daily at 16:46 Sweden Time (15:46 UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Run script and verify plot generation
        run: |
          # Run the Python script
          python autorun_daily.py

          # Expected files
          HEATMAP_FILE="daily heatmap/OMXS30_Sector_heatmap_${{ env.TIMESTAMP }}.png"
          HEATMAP2_FILE="daily heatmap/OMXS30_Sector_HeatMap_${{ env.TIMESTAMP }}.png"

          # Verify both plots exist
          if [ ! -f "$HEATMAP_FILE" ]; then
            echo "Expected plot not found: $HEATMAP_FILE. Exiting.";
            exit 1;
          fi

          if [ ! -f "$HEATMAP2_FILE" ]; then
            echo "Expected plot not found: $HEATMAP2_FILE. Exiting.";
            exit 1;
          fi

          # List the contents of the directory for debugging
          ls -la "daily heatmap/"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Add and commit the generated plots
          git add "daily heatmap/OMXS30_Sector_heatmap_${{ env.TIMESTAMP }}.png"
          git add "daily heatmap/OMXS30_Sector_HeatMap_${{ env.TIMESTAMP }}.png"
          git commit -m "Add plots for ${{ env.TIMESTAMP }}"
          git push origin main
