name: Run Autorun Daily Script

on:
  schedule:
    - cron: "46 16 * * *" # Run daily at 17:46 CET (adjusted for UTC during winter)
  workflow_dispatch: # Optional: Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token for authentication

      # Step 2: Set up Python
      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install --force-reinstall -r requirements.txt; fi

      # Step 4: Run the Python script
      - name: Run autorun_daily.py
        run: python autorun_daily.py

      # Step 5: Configure Git for committing changes
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 6: Commit and push the generated plots
      - name: Commit and push plots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add *.png
          git commit -m "Add daily plots for $(date +'%Y-%m-%d')"
          git push origin main
