import os
import subprocess
from datetime import datetime


def upload_plots_to_repo(folder="daily heatmap"):
    """
    Add and commit all PNG files in the specified folder to the Git repository.
    """
    # Check if the folder exists
    if not os.path.exists(folder):
        print(f"Folder '{folder}' does not exist. No plots to upload.")
        return

    # Collect all PNG files in the folder
    plot_files = [os.path.join(folder, f) for f in os.listdir(folder) if f.endswith(".png")]

    if not plot_files:
        print("No PNG files found to commit.")
        return

    print(f"Found {len(plot_files)} PNG files to commit: {plot_files}")

    # Add files to Git
    for plot in plot_files:
        result = subprocess.run(["git", "add", plot], capture_output=True, text=True)
        if result.returncode != 0:
            print(f"Error adding file {plot}: {result.stderr}")
            return

    # Commit message using current date
    today_date = datetime.now().strftime('%Y-%m-%d')
    commit_message = f"Add daily plots for {today_date}"

    # Commit and push changes
    result = subprocess.run(["git", "commit", "-m", commit_message], capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Error committing changes: {result.stderr}")
        return

    result = subprocess.run(["git", "push", "origin", "main"], capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Error pushing changes: {result.stderr}")
        return

    print(f"Successfully committed and pushed daily plots for {today_date}")


# Call the function
upload_plots_to_repo(folder="daily heatmap")
