name: Run Autorun Daily Script

on:
  schedule:
    - cron: "46 16 * * *" # Run daily at 17:46 CET
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Create target directory
      - name: Create daily heatmap folder
        run: mkdir -p "daily heatmap"

      # Generate timestamp for filenames
      - name: Generate timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Run script and save to folder
      - name: Run autorun_daily.py
        run: |
          python autorun_daily.py --output "daily heatmap/plot_${{ env.TIMESTAMP }}.png"

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Commit files from the folder
      - name: Commit and push plots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add "daily heatmap/plot_${{ env.TIMESTAMP }}.png"
          git commit -m "Add daily plot for ${{ env.TIMESTAMP }}"
          git push origin main
